name: Main workflow
on: push
env:
  docker_username: dlov507 
  docker_password: ${{ secrets.GITHUB_TOKEN }} 
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - run: ci/build-app.sh
      - name: Run Unit Tests
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  Linting:
      runs-on: ubuntu-latest
      needs: [Build]
      steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Build Docker Image
        run: bash ci/build-docker.sh

      - name: Push Docker Image
        run: bash ci/push-docker.sh

